// src/charts/react/block.js
/**
 * @description 指标块模型
 */
import React, { Component } from 'react';
import { raw } from '../raw';
import { JSX, charts } from '../constants';

const { METRIC_BLOCK } = charts;

const render = (v, index) => {
  switch (index) {
    case 0:
      return (<h2>{v}</h2>);
    case 1:
      return (<h3>{v}</h3>);
    default:
      return (<h4>{v}</h4>);
  }
};

raw
  .chart(METRIC_BLOCK)
  .category(JSX)
  .draw((canvas, cnf) => {
    const { name, metrics } = cnf;
    return (
      <div className="metric-list">
        {
          metrics.map(({ title, values }, index) => {
            const current = values[0];
            const left = values.slice(1);
            const { title: t, value, style } = current; // 本期
            const k = `b${index}`;
            return (
              <div key={k} className="metric-group">
                <div className="metric-group-item clearfix">
                  {
                    render(<span style={style}><span className="metric-block">{title}：</span>{value}</span>, index)
                  }
                  {
                    left.length ? (
                      <span className="pull-right">
                        ({
                          left.map(({ title, value, style }) => <span key={title} className="metric-block-ratio" style={style}><span>{title}：</span>{value}</span>, index)
                        })
                      </span>
                    ) : null
                  }
                </div>
              </div>
            );
          })
        }
      </div>
    );
  });

// src/charts/vue/block.vue
<template>
  <div class="metric-list">
    <div class="metric-group" v-for="(metric, index) in metrics" :key="index" >
      <div class="metric-group-item clearfix">
        <div :class="'m-h'+index">
          <span :style="metric.style">
            <span class="metric-block">{{metric.title}}：</span>{{metric.value}}
          </span>
        </div>
        <span className="pull-right">
          <span v-for="l in metric.left" :key="l.title" class="metric-block-ratio" :style="l.style">
            <span>{{l.title}}：</span>{{l.value}}
          </span>
        </span>
      </div>
    </div>
  </div>
</template>


<script>
import { raw } from '../raw';
import { JSX, charts } from '../constants';
const MetricBlock = {
  name: "MetricBlock",
  props: {
    config: Object,
    metrics: Array
  }
}
raw
  .chart(charts.METRIC_BLOCK)
  .category(JSX)
  .draw((createElement, data, config) => {
    if (Array.isArray(data.metrics)) {
      data.metrics = data.metrics.map((metric) => {
        const { title, values } = metric;
        const current = values[0];
        const left = values.slice(1);
        const { title: t, value, style } = current;
        return {
          ...metric,
          style,
          value,
          left
        };
      })
    }
    return createElement(MetricBlock, {
      props: data
    });
  });
export default MetricBlock;
</script>
<style>
  .m-h0 {
    font-size: 16px;
    font-weight: 500;
    color: rgba(0, 0, 0, 0.65);
  }
  .m-h1, .m-h2 {
    font-size: 14px;
    font-weight: 500;
    color: rgba(0, 0, 0, 0.65);
  }
</style>
